export const columns = [
  {
    Header: 'Supplier Name',
    accessor: 'supplier_name',
  },
  {
    Header: 'Compnay Name',
    accessor: 'supplier_company_name',
  },
  {
    Header: 'First Name',
    accessor: 'supplier_first_name',
  },
  {
    Header: 'Last Name',
    accessor: 'supplier_last_name',
  },
  {
    Header: 'Phone',
    accessor: 'supplier_phone',
  },
  {
    Header: 'Tax Rate',
    accessor: 'tax',
  },
  {
    Header: 'Address Line 1',
    accessor: 'supplier_address',
  },
  {
    Header: 'Address Line 2',
    accessor: 'supplier_address2',
  },
  {
    Header: 'City',
    accessor: 'city',
  },
  {
    Header: 'Province',
    accessor: 'division',
  },
  {
    Header: 'Country',
    accessor: 'country',
  },
  {
    Header: 'Post Code',
    accessor: 'postal_code',
  },
  {
    Header: 'Active',
    accessor: 'is_active',
  },
];

export const data = [
  {
    id: 1,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: 'Custom',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 2,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 3,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 4,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '011123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Ottawa Rd, Ottawa 1207',
    address_line_2: '',
    city: 'Ottawa',
    province: 'Ottawa',
    country: 'Canada',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 5,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 6,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 7,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 8,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 9,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 10,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 11,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 12,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 13,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 14,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 15,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 16,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 17,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 18,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 19,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 20,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 21,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 22,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 23,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 24,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 25,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 26,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 27,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 28,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 29,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 30,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
  {
    id: 31,
    supplier_name: 'Moslin Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 32,
    supplier_name: 'OnePeice Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Sohel',
    last_name: 'Rahman',
    phone: '018123456789',
    tax_rate: 'BD Government',
    address_line_1: '302/5, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '2207',
    active: 'Yes',
  },
  {
    id: 33,
    supplier_name: 'Jamdani Supplier',
    company_name: 'Somikoron Limited',
    first_name: 'Shuvo',
    last_name: 'Saleh',
    phone: '01762850108',
    tax_rate: '',
    address_line_1: '2201/1, Sukrabad Mirpur Rd, Dhaka 1207',
    address_line_2: 'First Floor',
    city: 'Dhaka',
    province: 'Dhaka',
    country: 'Bangladesh',
    postal_code: '1207',
    active: 'Yes',
  },
];
