from django.urls import path

from .import views

urlpatterns = [

    path('general/', views.GeneralSettingAPI.as_view(), name="general-setting"),
    path('edit_checkout_settings/',
         views.CheckoutSettingAPI.as_view(), name="checkout-setting"),
    path('edit_checkout_field_settings/',
         views.CheckouFieldtSettingAPI.as_view(), name="checkout-field-setting"),
    path('free_shipping/', views.FreeShippingMethodAPI.as_view(),
         name="free-shipping"),
    path('store_pickup_shipping/', views.StorePickupShippingMethodAPI.as_view(),
         name="store-pickup-shipping"),
    path('standard_shipping/', views.StandardShippingMethodAPI.as_view(),
         name="standard-shipping"),
    path('delivery_area/', views.DeliveryAreaAPI.as_view(), name="delivery-area"),
    path('edit_delivery_area/<int:pk>/', views.DeliveryAreaDetailAPI.as_view(), name="edit-delivery-area"),
    path('delivery_area/<str:country>/', views.DeliveryAreaCountryDetail.as_view(), name="DeliveryAreaCountryDetail"),
    path('regions/', views.RegionListAPI.as_view(), name="region"),
    path('tax-rates/', views.TaxRateList.as_view(), name="tax-rate-list"),
    path('tax-rate-details/<pk>/', views.TaxRateDetail.as_view(),
         name="tax-rate-details"),
    path('role/', views.RoleList.as_view(), name="role-list"),
    path('role-details/<pk>/', views.RoleDetails.as_view(), name="role-details"),
    path('resource/', views.ResourceList.as_view(), name="resource-list"),
    path('resource-details/<pk>/',
         views.ResourceDetails.as_view(), name="resource-details"),
    path('permission-role/', views.PermissionRoleList.as_view(),
         name="permission-role-list"),
    path('permission-role-details/<pk>/',
         views.PermissionRoleDetails.as_view(), name="permission-role-details"),
    path('operation/', views.OperationList.as_view(), name="operation-list"),
    path('operation-details/<pk>/',
         views.OperationDetails.as_view(), name="operation-details"),
    path('custom-user-list/', views.CustomUserList.as_view(),
         name="custom-user-list"),
    path('custom-user-details/<pk>/',
         views.CustomUserDetails.as_view(), name="custom-user-details"),
    path('activate-account/', views.ActivateCustomUserAccount.as_view(), name="activate-custom-user-account"),
    path('update-password/', views.CustomUserPasswordUpdate.as_view(), name="custom-user-password-update"),
    path('cash-on-payment/', views.CashonPaymentMethodAPI.as_view(), name="cash-on-payment-method"),
]
