export const columns = [
  {
    Header: 'Order ID',
    accessor: 'order_id',
    disableSortBy: true,
  },
  {
    Header: 'Customer',
    accessor: 'fullname',
    disableSortBy: true,
  },
  {
    Header: 'Phone Number',
    accessor: 'phone',
    disableSortBy: true,
  },
  {
    Header: 'Status',
    accessor: 'status',
    disableSortBy: true,
  },
  {
    Header: 'Fulfilment',
    accessor: 'is_fulfilled',
    disableSortBy: true,
  },
  {
    Header: 'Total Price',
    accessor: 'order_total',
    disableSortBy: true,
  },
  {
    Header: 'Order Type',
    accessor: 'order_type',
    disableSortBy: true,
  },
  {
    Header: 'Payment Method',
    accessor: 'payment_method',
  },
  {
    Header: 'Received at',
    accessor: 'created',
  },
  {
    Header: 'Actions',
    accessor: 'actions',
    disableSortBy: true,
  },
  {
    Header: 'Pathao',
    accessor: 'pathao_status',
    disableSortBy: false,
  },
];

export const data = [
  {
    id: 1,
    customer_id: '3',
    customer_username: 'sdkjfksdf',
    customer_email: 'sdkjfksdf@gmail.com',
    customer_phone: '',
    customer: 2,
    order_item: [],
    delivery_address: null,
    order_id: null,
    order_type: 'MANUAL ORDER',
    Order_reference: 'ONLINE-SALE',
    status: 'PENDING',
    ordered_by: 'gdfgdfdfg -admin',
    fullname: 'asdfasdf asdfasdf',
    email: 'sdkjfksdf@gmail.com',
    phone: '2947323',
    address: 'asdmkfa.s,d,fmkla fklasdjf af lka sfjkasl f;k sflasdf',
    order_note: 'al;skdjklf as;l ;a d;;',
    unit: 1,
    order_tracking_number: null,
    serial: null,
    separate_delivery_address: false,
    currency: 'BDT',
    has_discount: false,
    shipping_charge: '100.00',
    other_charges: '0.00',
    other_discount: '0.00',
    total_tax: '0.00',
    order_total: '2330.00',
    is_payment_successful: false,
    accepted_date: '2022-02-09T06:00:00+06:00',
    shipping_start_date: null,
    completed_date: null,
    expected_delivery_date: null,
    is_fulfilled: false,
    item_count: 27,
    product_list: '27',
    balance: '104.00',
    description: null,
    sales_note: 'adsfadf asdfasdf asdf',
    created: '2022-02-09T14:53:56.815173+06:00',
    updated: '2022-02-09T14:53:56.815173+06:00',
    promo_code: null,
    delivery_area: null,
    outlet: null,
    supplier: null,
    register: null,
    payment: null,
  },
  {
    id: 1,
    customer_id: '3',
    customer_username: 'sdkjfksdf',
    customer_email: 'sdkjfksdf@gmail.com',
    customer_phone: '',
    customer: 2,
    order_item: [],
    delivery_address: null,
    order_id: null,
    order_type: 'MANUAL ORDER',
    Order_reference: 'ONLINE-SALE',
    status: 'PENDING',
    ordered_by: 'gdfgdfdfg -admin',
    fullname: 'asdfasdf asdfasdf',
    email: 'sdkjfksdf@gmail.com',
    phone: '2947323',
    address: 'asdmkfa.s,d,fmkla fklasdjf af lka sfjkasl f;k sflasdf',
    order_note: 'al;skdjklf as;l ;a d;;',
    unit: 1,
    order_tracking_number: null,
    serial: null,
    separate_delivery_address: false,
    currency: 'BDT',
    has_discount: false,
    shipping_charge: '100.00',
    other_charges: '0.00',
    other_discount: '0.00',
    total_tax: '0.00',
    order_total: '400.00',
    is_payment_successful: false,
    accepted_date: '2022-02-09T06:00:00+06:00',
    shipping_start_date: null,
    completed_date: null,
    expected_delivery_date: null,
    is_fulfilled: false,
    item_count: 27,
    product_list: '27',
    balance: '104.00',
    description: null,
    sales_note: 'adsfadf asdfasdf asdf',
    created: '2022-02-09T14:53:56.815173+06:00',
    updated: '2022-02-09T14:53:56.815173+06:00',
    promo_code: null,
    delivery_area: null,
    outlet: null,
    supplier: null,
    register: null,
    payment: null,
  },
  {
    id: 1,
    customer_id: '3',
    customer_username: 'sdkjfksdf',
    customer_email: 'sdkjfksdf@gmail.com',
    customer_phone: '',
    customer: 2,
    order_item: [],
    delivery_address: null,
    order_id: null,
    order_type: 'MANUAL ORDER',
    Order_reference: 'ONLINE-SALE',
    status: 'PENDING',
    ordered_by: 'gdfgdfdfg -admin',
    fullname: 'asdfasdf asdfasdf',
    email: 'sdkjfksdf@gmail.com',
    phone: '2947323',
    address: 'asdmkfa.s,d,fmkla fklasdjf af lka sfjkasl f;k sflasdf',
    order_note: 'al;skdjklf as;l ;a d;;',
    unit: 1,
    order_tracking_number: null,
    serial: null,
    separate_delivery_address: false,
    currency: 'BDT',
    has_discount: false,
    shipping_charge: '100.00',
    other_charges: '0.00',
    other_discount: '0.00',
    total_tax: '0.00',
    order_total: '10400.00',
    is_payment_successful: false,
    accepted_date: '2022-02-09T06:00:00+06:00',
    shipping_start_date: null,
    completed_date: null,
    expected_delivery_date: null,
    is_fulfilled: false,
    item_count: 27,
    product_list: '27',
    balance: '104.00',
    description: null,
    sales_note: 'adsfadf asdfasdf asdf',
    created: '2022-02-09T14:53:56.815173+06:00',
    updated: '2022-02-09T14:53:56.815173+06:00',
    promo_code: null,
    delivery_area: null,
    outlet: null,
    supplier: null,
    register: null,
    payment: null,
  },
];
