# Generated by Django 3.2.7 on 2022-06-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_profile_api', '0001_initial'),
        ('inventory_api', '0001_initial'),
        ('app_api', '0002_initial'),
        ('customer_order_api', '0001_initial'),
        ('pos_api', '0001_initial'),
        ('settings_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='order_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_outlates', to='pos_api.outlet'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='order_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_outlates', to='pos_api.outlet'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='customer_order_api.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='inventory_api.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_size', to='inventory_api.productsizevariant'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='customer_profile_api.customerprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='customer_profile_api.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_api.deliveryarea'),
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_outlet', to='pos_api.outlet'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_orders', to='app_api.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos_api.register'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_supplier', to='inventory_api.supplier'),
        ),
    ]
