# Generated by Django 3.2.7 on 2022-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_api', '0001_initial'),
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections_promo_codes', to='inventory_api.ProductCategory'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_promo_codes', to='inventory_api.Product'),
        ),
    ]
